#server:
#  port: 1081
#
#spring:
#  application:
#    name: jml-cloud-authentication-serverless-service
#  main:
#    banner-mode: "console"
#
application:
  version: "@project.version@"

#  datasource:
#    url: jdbc:mysql://localhost:3306/application_table_db
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  security:
#    user:
#      name: admin
#      password: admin
#
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#
#cloud:
#  aws:
#    region: ${AWS_REGION:us-east-1}
#    bucket: ${AWS_S3_BUCKET_NAME}
#    credentials:
#      access-key: ${AWS_ACCESS_KEY_ID}
#      secret-key: ${AWS_SECRET_ACCESS_KEY}
#
#jwt:
#  secret: gOOKoiLpQ/XDAAo9I85L/2Bh3Y9KWvDFyRf7vqqGP38=
#  expiration: 3600000  # 1 hora en milisegundos
#  refreshExpirationMs: 14400000  # 3 horas en milisegundos
